# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/beyond1lte/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),beyond1lte)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G973F,126476b563c7a54a10edd724a6e0b5cfbc9e0532)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G973N,3762c3aa59a8a129e6628f0e4dee43cb4f6e25eb)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G973F,6169ec6eac7ea874ca4a0d4953d7b76ed3e53a7b)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G973N,597d40940b8fd35e68e2c42568cdc2b65abf018a)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G973F,92924d561c657d64d4b8004b6f6186eb9f39ecac)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G973N,fc260e8d95ce0fceec6a400298fe782015c714a8)
$(call add-radio-file-sha1-checked,radio/models,1ef6255117afcaec2ba8beb1a9e613d825abcf82)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G973F,eed1f1c002f2db36c820e03476f29a3655039c66)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G973N,1552eec6dfa02cd3292f67c051ebd8206011a928)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G973F,1931bf41b1749892abd91dc93fb94581df87e954)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G973N,c345b38e63b3298bddc039d79987fcced8343182)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G973F,9781693e991c4072a933ab3da2462fba28b7c577)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G973N,fbf8216294af7d982894a66a67cbb4443918a948)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G973F,ae553ae3e9eb8f6e852b653e26c3c973548a3418)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G973N,b38f066e660349f811a945add4d50d027aaa8b80)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G973F,d89bc2bf4d00952d94c6210ed1c755deda4fea14)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G973N,68d2e9edada459a5f3f60c75c6eab10ab1aca321)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G973F,b9e442728885aa115bcc903f4ca7bbfb8ae867ea)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G973N,d73f8be51f072cd74f5821f6b058637380ccf807)
$(call add-radio-file-sha1-checked,radio/version_SM-G973F,712415d711e12e35b021dd777306f3d99f2aae8d)
$(call add-radio-file-sha1-checked,radio/version_SM-G973N,9b653742a7bcfcdcbef3f20644bb01923cda1776)

endif
